apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-keyvault-template
  title: Azure Key Vault Provisioning
  description: Provision Azure Key Vaults with RBAC and role assignments
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      properties:
        serviceName:
          type: string
          description: Name of the service
          default: azure-keyvault-service

    - title: Key Vault Configuration
      properties:
        key_vault_name:
          type: string
          description: Name of the Key Vault
          default: iac-poc-kv-001
        resource_group_name:
          type: string
          description: Resource Group name
          default: test1
        enable_rbac_authorization:
          type: boolean
          default: true
        enabled_for_deployment:
          type: boolean
          default: true
        enabled_for_disk_encryption:
          type: boolean
          default: true
        enabled_for_template_deployment:
          type: boolean
          default: false
        purge_protection_enabled:
          type: boolean
          default: false
        sku_name:
          type: string
          enum: [standard, premium]
          default: standard
        soft_delete_retention_days:
          type: number
          default: 7
        network_acls:
          type: object
          properties:
            bypass:
              type: string
              default: AzureServices
            default_action:
              type: string
              default: Allow
            ip_rules:
              type: array
              items:
                type: string
              default: []
            virtual_network_subnet_ids:
              type: array
              items:
                type: string
              default: []

    - title: Role Assignment
      properties:
        role_definition_name:
          type: string
          default: Key Vault Crypto User
        user_names:
          type: array
          items:
            type: string
        group_names:
          type: array
          items:
            type: string
          default:
            - testg
        service_principal_names:
          type: array
          items:
            type: string
          default: []

  steps:
    - id: fetch-base
      name: Fetch Terraform Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          key_vault_name: ${{ parameters.key_vault_name }}
          resource_group_name: ${{ parameters.resource_group_name }}
          sku_name: ${{ parameters.sku_name }}
          soft_delete_retention_days: ${{ parameters.soft_delete_retention_days }}
          purge_protection_enabled: ${{ parameters.purge_protection_enabled }}
          enable_rbac_authorization: ${{ parameters.enable_rbac_authorization }}
          default_action: ${{ parameters.default_action }}
          bypass: ${{ parameters.bypass }}
          user_names: ${{ parameters.user_names }}
          group_names: ${{ parameters.group_names }}
          role_definition_name: ${{ parameters.role_definition_name }}
    - id: publish
      if: ${{ parameters.publish_to_github }}
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=sameerijoshi&repo=azure-keyvault-${{ parameters.key_vault_name }}
        description: Terraform for Azure Key Vault
        defaultBranch: main

  output:
    links:
      - title: Download dconf bundle (YAML)
        url: ${{ steps.fetch-base.output.basePath }}/dconf-bundle.yaml

      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
