apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-key-vault
  title: Azure Key Vault (RBAC)
  description: Create an Azure Key Vault using Terraform
spec:
  owner: platform-team
  type: infrastructure

  parameters:
    - title: Key Vault Configuration
      required:
        - key_vault_name
        - resource_group_name
      properties:
        key_vault_name:
          title: Key Vault Name
          type: string
          description: Name of the Azure Key Vault
        resource_group_name:
          title: Resource Group Name
          type: string
        sku_name:
          title: SKU
          type: string
          enum:
            - standard
            - premium
          default: standard
        soft_delete_retention_days:
          title: Soft Delete Retention (days)
          type: number
          default: 7
        purge_protection_enabled:
          title: Purge Protection Enabled
          type: boolean
          default: true
        enable_rbac_authorization:
          title: Enable RBAC Authorization
          type: boolean
          default: true

    - title: Network Configuration
      properties:
        default_action:
          title: Default Network Action
          type: string
          enum:
            - Allow
            - Deny
          default: Allow
        bypass:
          title: Bypass
          type: string
          enum:
            - AzureServices
            - None
          default: AzureServices

    - title: RBAC Role Assignment
      properties:
        user_names:
          title: User Principal Names
          type: array
          items:
            type: string
          description: Azure AD users
        group_names:
          title: Group Names
          type: array
          items:
            type: string
        role_definition_name:
          title: Role Definition
          type: string
          default: Key Vault Crypto User

  steps:
    - id: fetch-base
      name: Fetch Terraform Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          key_vault_name: ${{ parameters.key_vault_name }}
          resource_group_name: ${{ parameters.resource_group_name }}
          sku_name: ${{ parameters.sku_name }}
          soft_delete_retention_days: ${{ parameters.soft_delete_retention_days }}
          purge_protection_enabled: ${{ parameters.purge_protection_enabled }}
          enable_rbac_authorization: ${{ parameters.enable_rbac_authorization }}
          default_action: ${{ parameters.default_action }}
          bypass: ${{ parameters.bypass }}
          user_names: ${{ parameters.user_names }}
          group_names: ${{ parameters.group_names }}
          role_definition_name: ${{ parameters.role_definition_name }}
    - id: publish
      if: ${{ parameters.publish_to_github }}
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=sameerijoshi&repo=azure-keyvault-${{ parameters.key_vault_name }}
        description: Terraform for Azure Key Vault
        defaultBranch: main

  output:
    links:
      - title: Download dconf bundle (YAML)
        url: ${{ steps.fetch-base.output.basePath }}/dconf-bundle.yaml

      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
