apiVersion: dconf.io/v1
kind: Bundle
metadata:
  name: {{ key_vault_name }}
spec:
  keyVault:
    name: {{ key_vault_name }}
    resourceGroup: {{ resource_group_name }}
    sku: {{ sku_name }}
    softDeleteRetentionDays: {{ soft_delete_retention_days }}
    purgeProtectionEnabled: {{ purge_protection_enabled }}
    enableRbacAuthorization: {{ enable_rbac_authorization }}

  network:
    defaultAction: {{ default_action }}
    bypass: {{ bypass }}

  rbac:
    roleDefinitionName: {{ role_definition_name }}
    users:
{% for user in user_names %}
      - {{ user }}
{% endfor %}
    groups:
{% for group in group_names %}
      - {{ group }}
{% endfor %}
