{% if values.os_type == "Windows" %}
windows_vms:
  - name: "${{ values.vm_name }}"
    resource_group_name: "iac-poc-rg-001"
    key_vault_name: "iac-poc-kv-001"
    key_vault_resource_group_name: "iac-poc-rg-001"
    admin_password_secret_name: "winpass01"
    admin_username: "azureuser"
    size: "{{ values.sku }}"
    network_interface_names:
      - "nic-cus-app-dev-001"
    os_disk_storage_account_type: "StandardSSD_LRS"
    source_image_publisher: "MicrosoftWindowsServer"
    source_image_offer: "WindowsServer"
    source_image_sku: "2016-Datacenter"
    source_image_version: "latest"
{% else %}
windows_vms: []
{% endif %}

{% if values.os_type == "Linux" %}
linux_vms:
  - name: "${{ values.vm_name }}"
    resource_group_name: "poc-vijesh-tfstate"
    admin_username: "azureuser"
    key_vault_name: "vijesh-test-kv"
    key_vault_resource_group_name: "poc-vijesh-tfstate"
    size: "{{ values.sku }}"
    network_interface_names:
      - "nic-1"
    os_disk_storage_account_type: "Standard_LRS"
    source_image_offer: "UbuntuServer"
    source_image_publisher: "Canonical"
    source_image_sku: "16.04-LTS"
    source_image_version: "latest"
{% else %}
linux_vms: []
{% endif %}

{% if values.os_type == "Windows" %}
network_interfaces:
  - name: "nic-cus-app-dev-001"
    ip_configurations:
      - name: "ip-config-1"
        private_ip_address_allocation: "Dynamic"
        public_ip_name: null
        vnet_name: "iac-poc-vnet1"
        subnet_name: "iac-poc-snet1"
        vnet_rg_name: "iac-poc-rg-001"
{% else %}
network_interfaces:
  - name: "nic-1"
    ip_configurations:
      - name: "ip-config-1"
        vnet_name: "poc-vijesh-vnet"
        subnet_name: "snet1"
        vnet_resource_group_name: "poc-vijesh-tfstate"
        public_ip_name: null
{% endif %}

{% if values.os_type == "Windows" %}
attach_managed_disks:
  - managed_data_disk_name: "iac-poc-disk-001"
    virtual_machine_name: "vm-cus-app-dev-01"
{% else %}
attach_managed_disks:
  - virtual_machine_name: "{{ values.component_name }}"
    managed_data_disk_name: "ansibletest_OsDisk_1_3cdae46b541643a3acdcc04ea5aa84ab"
{% endif %}

{% if values.os_type == "Windows" %}
disk_init:
  - virtual_machine_names:
      - "vm-cus-app-dev-01"
    partition_style: "MBR"
    re_run: false
{% else %}
disk_init:
  - virtual_machine_name: "{{ values.component_name }}"
    re_run_disk_init: false
    partitions:
      - lun: 0
        size: "1GB"
        mount: "/disk-0-0"
{% endif %}