windows_vms:
  {% if values.os_type == "windows" %}
  {%- for wvm in values.vm_list %}
  - name: "{{ wvm.vm_name }}"
    resource_group_name: "{{ values.resource_group_name }}"
    key_vault_name: "{{ values.key_vault_name }}"
    key_vault_resource_group_name: "{{ values.resource_group_name }}"
    admin_password_secret_name: "{{ values.admin_password_secret_name }}"
    admin_username: "{{ values.admin_username }}"
    size: "{{ values.sku }}"
    network_interface_names:
      - "{{ values.nic_name }}-{{ loop.index }}"
    os_disk_storage_account_type: "{{ values.os_disk_type }}"
    source_image_publisher: "MicrosoftWindowsServer"
    source_image_offer: "WindowsServer"
    source_image_sku: "{{ values.os_version }}"
    source_image_version: "latest"
  {%- endfor %}
  {% endif %}

linux_vms:
  {% if values.os_type == "linux" %}
  {%- for lvm in values.vm_list %}
  - name: "{{ lvm.vm_name }}"
    resource_group_name: "{{ values.resource_group_name }}"
    admin_username: "{{ values.admin_username }}"
    key_vault_name: "{{ values.key_vault_name }}"
    key_vault_resource_group_name: "{{ values.resource_group_name }}"
    size: "{{ values.sku }}"
    network_interface_names:
      - "{{ values.nic_name }}-{{ loop.index }}"
    os_disk_storage_account_type: "{{ values.os_disk_type }}"
    source_image_offer: "UbuntuServer"
    source_image_publisher: "Canonical"
    source_image_sku: "{{ values.os_version }}"
    source_image_version: "latest"
  {%- endfor %}
  {% endif %}

network_interfaces:
  {%- for vm in values.vm_list %}
  - name: "{{ values.nic_name }}-{{ loop.index }}"
    ip_configurations:
      - name: "ip-config-{{ loop.index }}"
        vnet_name: "{{ values.vnet_name }}"
        subnet_name: "{{ values.subnet_name }}"
        vnet_resource_group_name: "{{ values.resource_group_name }}"
        public_ip_name: "{{ values.public_ip_name | default('null') }}"
  {%- endfor %}

attach_managed_disks:
  {%- for vm in values.vm_list %}
  - virtual_machine_name: "{{ vm.vm_name }}"
    managed_data_disk_name: "{{ values.managed_disk_name }}-{{ loop.index }}"
  {%- endfor %}

disk_init:
  {%- for vm in values.vm_list %}
  - virtual_machine_name: "{{ vm.vm_name }}"
    re_run_disk_init: false
    partitions:
      - lun: 0
        size: "{{ values.disk_size }}"
        mount: "{{ values.disk_mount }}"
  {%- endfor %}