# windows_vms: {%- for wvm in values.vm_list %}
#   instance0${{ loop.index }}:
#   {% if values.os_type == "windows" %}
#   - name: "${{ wvm.vm_name }}"
#     resource_group_name: "{{ values.resource_group_name }}"
#     key_vault_name: "{{ values.key_vault_name }}"
#     key_vault_resource_group_name: "{{ values.resource_group_name }}"
#     admin_password_secret_name: "{{ values.admin_password_secret_name }}"
#     admin_username: "{{ values.admin_username }}"
#     size: "{{ values.sku }}"
#     network_interface_names:
#       - "{{ values.nic_name }}"
#     os_disk_storage_account_type: "{{ values.os_disk_type }}"
#     source_image_publisher: "MicrosoftWindowsServer"
#     source_image_offer: "WindowsServer"
#     source_image_sku: "{{ values.os_version }}"
#     source_image_version: "latest"
#   {% endif %}
# {% endfor %}

# linux_vms: {%- for lvm in values.vm_list %}
#   instance0${{ loop.index }}:
#   {% if values.os_type == "linux" %}
#   - name: "${{ lvm.vm_name }}"
#     resource_group_name: "{{ values.resource_group_name }}"
#     admin_username: "{{ values.admin_username }}"
#     key_vault_name: "{{ values.key_vault_name }}"
#     key_vault_resource_group_name: "{{ values.resource_group_name }}"
#     size: "{{ values.sku }}"
#     network_interface_names:
#       - "{{ values.nic_name }}"
#     os_disk_storage_account_type: "{{ values.os_disk_type }}"
#     source_image_offer: "{{ values.os_offer }}"
#     source_image_publisher: "{{ values.os_publisher }}"
#     source_image_sku: "{{ values.os_version }}"
#     source_image_version: "latest"
#   {% endif %}
# {% endfor %}

# network_interfaces:
#   - name: "{{ values.nic_name }}"
#     ip_configurations:
#       - name: "ip-config-1"
#         vnet_name: "{{ values.vnet_name }}"
#         subnet_name: "{{ values.subnet_name }}"
#         vnet_resource_group_name: "{{ values.resource_group_name }}"
#         public_ip_name: "{{ values.public_ip_name | default('null') }}"

# attach_managed_disks:
#   - virtual_machine_name: "{{ values.component_name }}"
#     managed_data_disk_name: "{{ values.managed_disk_name }}"

# disk_init:
#   - virtual_machine_name: "{{ values.component_name }}"
#     re_run_disk_init: false
#     partitions:
#       - lun: 0
#         size: "{{ values.disk_size }}"
#         mount: "{{ values.disk_mount }}"

windows_vms:
  {% if values.os_type == "windows" %}
  - name: "{{ values.vm_name }}"
    resource_group_name: "{{ values.resource_group_name }}"
    key_vault_name: "{{ values.key_vault_name }}"
    key_vault_resource_group_name: "{{ values.resource_group_name }}"
    admin_password_secret_name: "{{ values.admin_password_secret_name }}"
    admin_username: "{{ values.admin_username }}"
    size: "{{ values.sku }}"
    network_interface_names:
      - "{{ values.nic_name }}"
    os_disk_storage_account_type: "{{ values.os_disk_type }}"
    source_image_publisher: "MicrosoftWindowsServer"
    source_image_offer: "WindowsServer"
    source_image_sku: "{{ values.os_version }}"
    source_image_version: "latest"
  {% endif %}

linux_vms:
  {% if values.os_type == "linux" %}
  - name: "{{ values.vm_name }}"
    resource_group_name: "{{ values.resource_group_name }}"
    admin_username: "{{ values.admin_username }}"
    key_vault_name: "{{ values.key_vault_name }}"
    key_vault_resource_group_name: "{{ values.resource_group_name }}"
    size: "{{ values.sku }}"
    network_interface_names:
      - "{{ values.nic_name }}"
    os_disk_storage_account_type: "{{ values.os_disk_type }}"
    source_image_offer: "UbuntuServer"
    source_image_publisher: "Canonical"
    source_image_sku: "{{ values.os_version }}"
    source_image_version: "latest"
  {% endif %}

network_interfaces:
  - name: "{{ values.nic_name }}"
    ip_configurations:
      - name: "ip-config-1"
        vnet_name: "{{ values.vnet_name }}"
        subnet_name: "{{ values.subnet_name }}"
        vnet_resource_group_name: "{{ values.resource_group_name }}"
        public_ip_name: "{{ values.public_ip_name | default('null') }}"

attach_managed_disks:
  - virtual_machine_name: "{{ values.component_name }}"
    managed_data_disk_name: "{{ values.managed_disk_name }}"

disk_init:
  - virtual_machine_name: "{{ values.component_name }}"
    re_run_disk_init: false
    partitions:
      - lun: 0
        size: "{{ values.disk_size }}"
        mount: "{{ values.disk_mount }}"